Removed a number of RPMs that lead to conflicts during yum updates.
Example:
"Error: Package: libdrm-devel-2.4.59-2.el6.x86_64 (/libdrm-devel-2.4.59-2.el6.x86_64)
            Requires: libdrm = 2.4.59-2.el6
            Installed: libdrm-2.4.65-2.el6.x86_64 (@base)
                libdrm = 2.4.65-2.el6
 Error: Package: libxcb-devel-1.9.1-3.el6.x86_64 (/libxcb-devel-1.9.1-3.el6.x86_64)
            Requires: libxcb = 1.9.1-3.el6
            Available: libxcb-1.11-2.el6.i686 (base)
                libxcb = 1.11-2.el6"

Former-commit-id: fe671bd14d38189395d662e3c18540b1a9fc0ff1